app/api/urls.py
from django.urls import path
from api import views

app_name = 'api'


urlpatterns = [
    path('car/stories/<vin_code>/', views.CarStoryListView.as_view(), name='car_stories'),
    path('service-station/details/<pk>/', views.ServiceStationDetailsView.as_view(), name='service_station_details'),
    path('service-station/rating/list/', views.ServiceStationRatingListView.as_view(),
         name='service_station_rating_list')
    ]

app/comments_and_rating/urls.py
from django.urls import path
from comments_and_rating import views

app_name = 'comments_and_rating'


urlpatterns = [
    path('create/comments_and_rating/<str:check_number>/', views.CommentAndRatingCreateView.as_view(),
         name='create_comments_and_rating'),
    path('services-stations/rating/list/', views.ServiceStationsRatingListView.as_view(),
         name='service_stations_rating')
    ]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from autohistory.views import IndexView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('autohistory/', include('autohistory.urls')),
    path('comments_and_rating/', include('comments_and_rating.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/parts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto history</title>
</head>
<body>
{% include 'parts/navbar.html' %}

{% block main_content %}
{% endblock main_content %}


</body>
</html>

app/templates/parts/navbar.html
<div>
    <a href="/">На головну</a>
    <a href="{% url 'comments_and_rating:service_stations_rating' %}">Рейтинг станцій</a>
</div>

app/templates/parts/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&{{ filter_params }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&{{ filter_params }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"&{{ filter_params }}>last &raquo;</a>
        {% endif %}
    </span>
</div>