app/accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('auth/', include('django.contrib.auth.urls')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('create/service-station/', views.ServiceStationCreateView.as_view(), name='create_service_station'),
    path('list/service-station/', views.ServiceStationListView.as_view(), name='list_service_station'),
    path('details/service-station/<int:pk>/', views.ServiceStationDetailView.as_view(), name='details_service_station'),
    path('update/service-station/<int:pk>/', views.ServiceStationUpdateView.as_view(), name='update_service_station'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='activate')
    ]

app/api/urls.py
from django.urls import path
from api import views

app_name = 'api'


urlpatterns = [
    path('car/stories/<vin_code>/', views.CarStoryListView.as_view(), name='car_stories'),
    path('service-station/details/<pk>/', views.ServiceStationDetailsView.as_view(), name='service_station_details'),
    path('service-station/rating/list/', views.ServiceStationRatingListView.as_view(),
         name='service_station_rating_list')
    ]

app/autohistory/urls.py
from django.urls import path
from autohistory import views

app_name = 'autohistory'


urlpatterns = [
    path('create/autohistory/', views.CarStoryCreateHistoryView.as_view(), name='create_auto_history'),
    path('details/<int:pk>/', views.CarStoryHistoryDetailView.as_view(), name='history_details'),
    path('car-story/list/<str:pk>/', views.CarStoriesListView.as_view(), name='car_story'),
    # path('details/car-story/service-station/<str:pk>/', views.CarStoryServiceStationsDataView.as_view(),
    #      name='car_story_service_station_details'),
    path('damage/photos/<int:pk>/', views.CarDamagePhotosListView.as_view(), name='damage_photos'),
    ]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from autohistory.views import IndexView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('autohistory/', include('autohistory.urls')),
    path('comments_and_rating/', include('comments_and_rating.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/autohistory/models.py
from django.db import models
from autohistory.model_choices import MileageUnitType
from accounts.models import ServiceStation
import datetime


def photo_mileage(instance, filename):
    data = datetime.datetime.now()
    return 'mileage_photo/{}/{}/{}/{}/{}/{}'.format(data.year, data.month, data.day, instance.vin_code,
                                                       instance.service_station_name.station_name, filename)


def photo_damages(instance, filename):
    data = datetime.datetime.now()
    return 'damages_photo/{}/{}/{}/{}/{}/{}'.format(data.year, data.month, data.day, instance.car_story.vin_code,
                                                       instance.car_story.service_station_name.station_name, filename)


class CarStory(models.Model):
    vin_code = models.CharField(max_length=17)
    mileage_units = models.CharField(max_length=2, choices=MileageUnitType.choices)
    mileage = models.IntegerField()
    mileage_photo = models.ImageField(upload_to=photo_mileage, null=True)
    service_station_name = models.ForeignKey('accounts.ServiceStation', on_delete=models.DO_NOTHING)
    damage = models.TextField(max_length=1000)
    work = models.TextField(max_length=10000)
    check_number = models.CharField(max_length=22)
    created = models.DateField(auto_now_add=True)


class DamagePhoto(models.Model):
    car_story = models.ForeignKey('CarStory', on_delete=models.DO_NOTHING)
    photo = models.ImageField(upload_to=photo_damages, null=True, blank=True)

app/autohistory/forms.py
from django import forms

from accounts.models import ServiceStation
from autohistory.models import CarStory


class CarForm(forms.ModelForm):
    damage_photo = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False,
                                   label=("Завантажте фотографіх пошкоджень"))
    email = forms.EmailField(label="Введіть пошту кліета")

    class Meta:
        model = CarStory
        fields = (
            'vin_code',
            'mileage_units',
            'mileage',
            'mileage_photo',
            'service_station_name',
            'damage',
            'work',
            'check_number',
        )
        labels = {

            'vin_code': 'Він-код',
            'mileage_units': 'Одиниці виміру',
            'mileage': 'Пробіг',
            'mileage_photo': 'Завантажте фото одометру',
            'service_station_name': 'Назва СТО',
            'damage': 'Пошкодження',
            'work': 'Роботи',
            'check_number': 'Фіскальний номер чека',

        }

    def __init__(self, *args, **kwargs):
        user_id = kwargs['initial']['company']
        super().__init__(*args, **kwargs)
        self.fields['service_station_name'].queryset = ServiceStation.objects.filter(company=user_id)


class SearchCarHistoryForm(forms.Form):
    vin = forms.CharField(max_length=17, min_length=17)

app/autohistory/views.py
from autohistory.models import CarStory, DamagePhoto
from autohistory.forms import CarForm, SearchCarHistoryForm
from django.views import generic
from django.urls import reverse_lazy, reverse
from accounts.models import ServiceStation
from autohistory.tasks import send_link_for_comment
from django.http import Http404


class IndexView(generic.FormView):
    template_name = 'index.html'
    form_class = SearchCarHistoryForm

    def form_valid(self, form):
        vin = form.cleaned_data.get('vin')
        self.success_url = reverse('autohistory:car_story', kwargs={'pk': vin})
        return super().form_valid(form)


class CarStoriesListView(generic.ListView):
    template_name = 'my_auto_history.html'
    paginate_by = 5

    def get_queryset(self, **kwargs):
        vin_code = self.kwargs['pk']
        queryset = CarStory.objects.filter(vin_code=vin_code).order_by('-created').all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vin_code'] = self.kwargs['pk']
        return context


class CarStoryCreateHistoryView(generic.CreateView):
    queryset = CarStory.objects.all()
    template_name = 'create_auto_history.html'
    form_class = CarForm
    success_url = reverse_lazy('index')

    def get_form_kwargs(self):
        instance = super().get_form_kwargs()
        instance['initial'] = {'company': self.request.user.id}
        return instance

    def form_valid(self, form):

        car = form.save()

        send_link_for_comment.delay(form.cleaned_data['check_number'], form.cleaned_data['email'])

        damage_photos = self.request.FILES.getlist('damage_photo')
        for photo in damage_photos:
            DamagePhoto.objects.create(photo=photo, car_story=car)
        return super().form_valid(form)


class CarStoryHistoryDetailView(generic.DetailView):
    queryset = CarStory.objects.select_related('commentsandratings').all()
    template_name = 'auto_history_details.html'


# class CarStoryServiceStationsDataView(generic.DetailView):
#     queryset = ServiceStation.objects.all()
#     template_name = 'car_story_services_stations.html'


class CarDamagePhotosListView(generic.ListView):
    queryset = DamagePhoto.objects.all()
    template_name = 'damage_photos.html'

    def get_queryset(self):
        car_story_id = self.kwargs['pk']
        queryset = DamagePhoto.objects.filter(car_story=car_story_id).all()
        return queryset

app/autohistory/templates/auto_history_details.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <div>
        СТО: <a href="{% url 'accounts:details_service_station' object.service_station_name.id %}">{{ object.service_station_name.station_name }}</a>
        , Пробіг:{{ object.mileage }}{{ object.mileage_units }}
        ,Пошкодження: <a href="{% url 'autohistory:damage_photos' object.id %}"> {{ object.damage }}</a>
        ,Роботи: {{ object.work }}<br> Чек: {{ object.check_number }}
        <br>
        Фото одометра : <img src="{{ object.mileage_photo.url }}" height="120" width="120">
    </div>
    <a href="{% url 'autohistory:car_story' object.vin_code %}"> До інших записів</a>
{% endblock main_content %}

app/autohistory/templates/car_story_services_stations.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <div>
       Назва: {{ servicestation.station_name }} ,Місто: {{ servicestation.city }},Адресса {{ servicestation.address }}
       Номер телефону: {{ servicestation.phone }} ,Пошта: {{ servicestation.email }}
    </div>
{% endblock main_content %}

app/autohistory/templates/create_auto_history.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберігти</button>
    </form>
{% endblock main_content %}

app/autohistory/templates/damage_photos.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <div>
    Пошкодження:
        <br>
    {% for item in damagephoto_list %}
        <img src="{{ item.photo.url }}" height="120" width="120">
    {% endfor %}
    </div>
{% endblock main_content %}

app/autohistory/templates/index.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <div>
    {% if request.user.is_authenticated %}
        <a href="{% url 'autohistory:create_auto_history' %}"> Зробити запис </a>
        <a href="{% url 'accounts:profile' %}">Мій профіль</a>
        <a href="{% url 'accounts:list_service_station'%}">Мої Станції</a>
        <a href="{% url 'accounts:logout' %}">Вийти</a>
    {% else %}
        <a href="{% url 'accounts:signup' %}">Зареєструватись</a>
        <a href="{% url 'accounts:login' %}">Увійти</a>
    {% endif %}
    </div>

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Пошук</button>
    </form>
{% endblock main_content %}

app/autohistory/templates/my_auto_history.html
{% extends 'parts/base.html' %}3

{% block main_content %}
    <h3> Він-код: {{ vin_code }} </h3>
    <div>
    {% for item in carstory_list %}
        <p>
        Пробіг: {{ item.mileage }} {{ item.mileage_units }}, Дата: {{ item.created }}
            <a href="{% url 'autohistory:history_details' item.id %}"> Детальніше </a>
        </p>
    {% endfor %}
    </div>

    {% include 'parts/pagination.html' %}

{% endblock main_content %}

app/autohistory/templates/no_results.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <h2>На жаль нічого не знайдено</h2>
{% endblock main_content %}