app/accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('auth/', include('django.contrib.auth.urls')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('create/service-station/', views.ServiceStationCreateView.as_view(), name='create_service_station'),
    path('list/service-station/', views.ServiceStationListView.as_view(), name='list_service_station'),
    path('details/service-station/<int:pk>/', views.ServiceStationDetailView.as_view(), name='details_service_station'),
    path('update/service-station/<int:pk>/', views.ServiceStationUpdateView.as_view(), name='update_service_station'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='activate')
    ]

app/api/urls.py
from django.urls import path
from api import views

app_name = 'api'


urlpatterns = [
    path('car/stories/<vin_code>/', views.CarStoryListView.as_view(), name='car_stories'),
    path('service-station/details/<pk>/', views.ServiceStationDetailsView.as_view(), name='service_station_details'),
    path('service-station/rating/list/', views.ServiceStationRatingListView.as_view(),
         name='service_station_rating_list')
    ]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from autohistory.views import IndexView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('autohistory/', include('autohistory.urls')),
    path('comments_and_rating/', include('comments_and_rating.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.core.validators import MinLengthValidator, MaxLengthValidator


def station_avatar(instance, filename):
    data = datetime.datetime.now()
    return 'station_avatar/{}/{}/{}/{}/{}/{}'.format(data.year, data.month, data.day,
                                                     instance.station_name, instance.company.id, filename)


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    email = models.EmailField("email address", unique=True)
    EDRPOU = models.IntegerField(unique=True, null=True, default=None)
    company_name = models.CharField(max_length=120, null=True, default=None)


class ServiceStation(models.Model):
    station_name = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=128)
    email = models.EmailField(unique=True)
    station_avatar = models.ImageField(upload_to=station_avatar,
                                       default='accounts/images/default_station_photo.jpeg', null=True)
    company = models.ForeignKey('accounts.User', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.station_name

app/accounts/forms.py
import uuid

from django import forms
from django.contrib.auth import get_user_model
from accounts.models import ServiceStation
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from autohistory.tasks import send_activate_mail


class SignUpForm(forms.ModelForm):
    password_confirmation = forms.CharField(label='Підтвердження пароля')

    class Meta:
        model = get_user_model()
        fields = [
            'email',
            'password',
        ]
        labels = {'email': 'Пошта',
                  'password': 'Пароль',
                  }

    def clean(self):
        cleaned_data = super().clean()
        if not self.errors:
            if cleaned_data['password'] != cleaned_data['password_confirmation']:
                raise forms.ValidationError("Паролі не співпадають")

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.username = str(uuid.uuid4())
        instance.is_active = False
        instance.set_password(self.cleaned_data['password'])

        if commit:
            instance.save()

        send_activate_mail.delay(instance.username, instance.email)

        return instance


class ProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = [
            'EDRPOU',
            'company_name'
        ]
        labels = {
            'EDRPOU': 'ЄДРПОУ',
            'company_name': 'Назва команії'
        }

    def clean_EDRPOU(self):
        edrpou = self.cleaned_data['EDRPOU']
        if len(str(edrpou)) != 8:
            raise forms.ValidationError("Невірна довжина ЄДРПОУ. Допустима лише 8 символів.")
        return edrpou


class ServiceStationForm(forms.ModelForm):
    class Meta:
        model = ServiceStation
        fields = [
            'station_name',
            'city',
            'address',
            'phone',
            'email',
            'station_avatar',
            'company'
        ]
        labels = {
            'station_name': 'Назва станції',
            'city': 'Місто',
            'address': 'Адреса',
            'phone': 'Номер телефону',
            'email': 'Пошта',
            'station_avatar': 'Завантажте фото станції'
        }
        widgets = {'company': forms.HiddenInput()}

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.initial['company']
        if commit:
            instance.save()
        return instance


class ServiceStationUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceStation
        fields = [
            'station_name',
            'city',
            'address',
            'phone',
            'email',
            'station_avatar'
        ]
        labels = {
            'station_name': 'Назва станції',
            'city': 'Місто',
            'address': 'Адреса',
            'phone': 'Номер телефону',
            'email': 'Пошта',
            'station_avatar': 'Змінити фото станції'
        }

app/accounts/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from accounts.forms import SignUpForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from accounts.models import ServiceStation
from accounts.forms import ProfileForm, ServiceStationForm, ServiceStationUpdateForm


class SignUpView(generic.CreateView):
    model = get_user_model()
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = reverse_lazy('accounts:login')


class ProfileView(generic.UpdateView):
    model = get_user_model()
    form_class = ProfileForm
    template_name = 'profile.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return self.request.user


class ServiceStationCreateView(generic.CreateView):
    model = ServiceStation
    form_class = ServiceStationForm
    template_name = 'create_service_station.html'
    success_url = reverse_lazy('autohistory:create_auto_history')

    def get_form_kwargs(self):
        instance = super().get_form_kwargs()
        instance['initial'] = {'company': self.request.user}
        return instance


class ServiceStationListView(generic.ListView):
    model = ServiceStation
    template_name = 'list_service_station.html'


class ServiceStationDetailView(generic.DetailView):
    model = ServiceStation
    template_name = 'details_service_station.html'


class ServiceStationUpdateView(generic.UpdateView):
    model = ServiceStation
    form_class = ServiceStationUpdateForm
    template_name = 'update_service_station.html'
    success_url = reverse_lazy('accounts:list_service_station')


class UserActivateView(generic.RedirectView):
    pattern_name = 'index'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username')
        user = get_object_or_404(get_user_model(), username=username)

        if user.is_active:
            pass
        else:
            user.is_active = True
            user.save()

        response = super().get(request, *args, **kwargs)
        return response

app/accounts/templates/create_service_station.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберігти</button>
    </form>
{% endblock main_content %}

app/accounts/templates/details_service_station.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <div>
        <img src="{{ servicestation.station_avatar.url }}" height="120" width="120">
        <br>
       Назва: {{ servicestation.station_name }} ,Місто: {{ servicestation.city }},Адресса {{ servicestation.address }}
       Номер телефону: {{ servicestation.phone }} ,Пошта: {{ servicestation.email }}

    </div>
    <a href="{% url 'accounts:list_service_station' %}"> До списку станцій</a>
{% endblock main_content %}

app/accounts/templates/list_service_station.html
{% extends 'parts/base.html' %}3

{% block main_content %}
    <div>
    <a href="{% url 'accounts:create_service_station'%}">Додати станцію</a>
    {% for item in servicestation_list %}
        <p>
        Назва Станції : {{ item.station_name }}, Місто : {{ item.city}}, Адреса: {{ item.address }}
            <a href="{% url 'accounts:details_service_station' item.id %}">Детальніше</a>
            <a href="{% url 'accounts:update_service_station' item.id %}">Змінити</a>
        </p>
    {% endfor %}
    </div>
{% endblock main_content %}

app/accounts/templates/profile.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <a href="{% url 'password_change' %}">Змінити Пароль</a>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберігти</button>
    </form>
{% endblock main_content %}

app/accounts/templates/signup.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Створити</button>
    </form>
{% endblock main_content %}

app/accounts/templates/update_service_station.html
{% extends 'parts/base.html' %}

{% block main_content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберігти</button>
    </form>
{% endblock main_content %}